# Generated by Django 4.2.2 on 2023-07-03 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
