# Generated by Django 4.2.3 on 2023-07-05 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_full_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="block_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="is_blocked",
            field=models.BooleanField(default=False),
        ),
    ]
