# Generated by Django 4.2.2 on 2023-07-03 21:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0003_book_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="number_copies",
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
