# Generated by Django 4.2.2 on 2023-07-04 00:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0004_book_number_copies"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="user",
            new_name="follower",
        ),
    ]
