# Generated by Django 4.2.2 on 2023-07-07 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_number_copies'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='availability',
            field=models.BooleanField(default=True),
        ),
    ]
