# Generated by Django 4.2.2 on 2023-07-01 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('copies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('return_date', models.DateField()),
                ('status', models.BooleanField(default=False)),
                ('copy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='copies.copy')),
            ],
        ),
    ]
