# Generated by Django 4.2.2 on 2023-07-01 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
