# Generated by Django 4.2.2 on 2023-07-03 21:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("loans", "0003_loan_updated_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="loan",
            old_name="status",
            new_name="is_finished",
        ),
    ]
